### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [Piashsarker/AndroidEasyUtils#2]
Hi...

Came across your FANTASTIC project... and as a skilled logo designer who loves contributing to open source projects, I want to help contribute to your project by creating a LOGO to give an identity and fully represent the idea of your project...

I am currently working on some logo concepts
I will post the finished concepts here for you to look at it and give your feedbacks about it.

Regards.

**Comment by Piashsarker** [comment]
Yes , you can provide the image in sarkerpt@gmail.com. 
I am resolving this issue.
